Fix: Use page description to guide learners who are using the gitbook learning resource
Ifycode/git-github-training-documentation pull request #75
Opened 2022-10-26 21:01 UTC by oyenuga17

**This pull request makes the following changes:**
* Fixes issue #65 

**Checklist:**
- [x] File or folder now contains changes as specified in the issue i worked on
- [x] I have linked the issue I worked on to this pull request submitted by me
- [x] I certify that I ran my checklist.

Ping @Ifycode/git-github-training-resource

2022-10-26 21:02 UTC, oyenuga17 commented
I just made changes please review ..finally understood @Ifycode

2022-10-27 04:20 UTC, Ifycode commented
Ok. Nice. Welldone @oyenuga17

2022-10-27 04:22 UTC, Ifycode requested changes

2022-10-27 04:22 UTC, Ifycode commented on doc/contributors-guide/contributing-guidelines.md
> -{% endhint %}
You were not told to replace or remove the hint. Please put this hint back @oyenuga17.

2022-11-02 01:53 UTC, merged