Fix page description
Ifycode/git-github-training-documentation pull request #83
Opened 2023-03-22 10:08 UTC by samuko-things

**This pull request makes the following changes:**
* Fixes issue #79
* Fixes issue #63

**Checklist:**
- [x] File or folder now contains changes as specified in the issue i worked on
- [x] I have linked the issue I worked on to this pull request submitted by me
- [x] I certify that I ran my checklist.

Ping @Ifycode/git-github-training-resource

2023-03-22 10:10 UTC, samuko-things commented
@Ifycode, I've just fixed issues 79 and 63 and this is the pull request, I'd like you to review it.

2023-03-22 18:51 UTC, Ifycode requested changes

2023-03-22 18:51 UTC, Ifycode commented on doc/part-1-github-ui/workflows-and-best-practices.md
> +You will learn the following from the learning videos on this page:
Neatly done @samuko-things 👍🏽
But change this line to "You will learn the following in this section:"

2023-03-23 19:34 UTC, Ifycode commented
@samuko-things I'm waiting for your changes so that I can move this repo.

2023-03-28 09:33 UTC, samuko-things commented
i have made the 

> @samuko-things I'm waiting for your changes so that I can move this repo.

I have made the change pls check it out.

2023-03-28 12:44 UTC, Ifycode approved these changes

2023-03-28 12:44 UTC, Ifycode commented on doc/part-1-github-ui/workflows-and-best-practices.md
> +
Approved 🎉

2023-03-28 12:44 UTC, merged